# Generated by Django 4.0 on 2022-01-01 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='tax_value',
        ),
    ]
