# Generated by Django 4.0 on 2022-01-02 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('invoice', '0002_remove_invoice_tax_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.ForeignKey(blank=True, default=3, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.duedate'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_state', to='common.invoicestate'),
        ),
    ]
